// ==============================================================================
// ODIN UI MANAGER - Main UI Controller (FIXED VERSION)
// ==============================================================================
// Manages the overlay panel, tabs, and all UI state
// Version: 5.0.0 
(function() {
  'use strict';

  window.OdinModules = window.OdinModules || [];
  window.OdinModules.push(function OdinUIManagerModuleInit(OdinContext) {
    const ctx = OdinContext || {};
    const storage = ctx.storage || { getJSON: () => null, setJSON: () => {} };
    const nexus = ctx.nexus || { emit: () => {}, on: () => () => {} };
    const log = ctx.log || console.log;
    const error = ctx.error || console.error;

    const UI_VERSION = '4.2.0';

    // ============================================
    // UI STATE
    // ============================================
    let isVisible = false;
    let activeTab = 'warRoom';
    let panelElement = null;
    let toggleButton = null;
    let apiKeysDirty = { torn: false, tornStats: false, ffScouter: false };

    // ============================================
    // AUTH / CONNECTION STATE
    // ============================================
    let firebaseConnected = !!ctx.firebase?.isConnected?.();
    let authUserPresent = !!(ctx.firebase?.getCurrentUser?.() || ctx.firebase?.auth?.()?.currentUser);

    const tabs = {
      warRoom: { label: '⚔️ War Room', component: null },
      targets: { label: '🎯 Targets', component: null },
      chain: { label: '⛓️ Chain', component: null },
      schedule: { label: '📅 Schedule', component: null },
      leadership: { label: '👑 Leadership', component: null },
      personal: { label: '👤 Personal', component: null },
      settings: { label: '⚙️ Settings', component: null }
    };

    // ============================================
    // AUTH GATING
    // ============================================
    const AUTH_REQUIRED_TABS = new Set(['warRoom', 'targets', 'chain', 'schedule', 'leadership', 'personal']);

    function isAuthReady() {
      // Check if user enabled local mode
      const localMode = storage && typeof storage.getJSON === 'function' ? storage.getJSON('odin_local_mode_v1') : false;
      if (localMode) return true;

      return !!firebaseConnected && !!authUserPresent;
    }

    function getSavedTornKey() {
      try { return (ctx.api && typeof ctx.api.getTornApiKey === 'function') ? (ctx.api.getTornApiKey() || '') : ''; } catch (_) { return ''; }
    }

    function renderAuthGate(tabId) {
      const saved = getSavedTornKey();
      const savedMasked = saved && saved.length > 8 ? (saved.slice(0, 4) + '••••••••' + saved.slice(-4)) : '';
      const status = firebaseConnected ? (authUserPresent ? 'Authenticated' : 'Connected') : 'Connecting';

      return `
        <div class="odin-card odin-auth-card">
          <div class="odin-card-header">
            <div class="odin-card-title">🔒 Authentication Required</div>
          </div>

          <div class="odin-auth-shell">
            <div class="odin-auth-info">
              <div class="odin-auth-info-line">This tab requires Firebase authentication for your faction.</div>
              <div class="odin-auth-status">Status: ${status}</div>
            </div>

            <div class="odin-auth-scroll" aria-label="Torn API Key Disclosure">
              <div class="odin-auth-disclaimer-title">Torn API Key Usage &amp; Security Disclosure</div>
              <div class="odin-auth-disclaimer-body">
                <h4>What a Torn API Key Is</h4>
                <p>A Torn API key is a personal access token generated by your Torn City account. It allows third-party tools to request game data from Torn’s official API without using your Torn password.</p>
                <p><strong>Important facts:</strong> Torn API keys do not grant account control, cannot perform gameplay actions (such as attacking, trading, or spending money), are commonly used by faction tools and war utilities, and can be revoked or regenerated at any time from your Torn account settings.</p>

                <h4>How Odin Tools Uses Your API Key</h4>
                <p>Odin Tools uses your API key to make direct, read-only requests to Torn’s official API from your browser. The key may be used to identify your player ID, identify your faction ID, fetch faction and war-related data required for Odin features, and enable live updates for war/chain tools.</p>
                <p>All Torn API requests go directly to <code>api.torn.com</code>, are only made when a feature requires them, and Odin Tools does not automate gameplay or perform actions on your behalf.</p>

                <h4>How Your API Key Is Stored</h4>
                <p>When you authenticate, your API key is automatically saved locally on your device so you do not need to enter it again. The key is stored only in your browser and is used by the script to make Torn API requests as needed. You may remove or replace the key at any time by clearing local data or regenerating the key in Torn.</p>

                <h4>One-Time Database Authentication</h4>
                <p>Your Torn API key is used to authenticate you with Odin’s backend a single time. Your browser submits your API key for validation, Torn confirms your player ID and faction ID, and Odin issues a secure authentication token tied to your Torn identity.</p>
                <p>All future database access uses this token instead of your API key. The API key is not used for ongoing database access. Database permissions are scoped to your Torn identity and faction. Regenerating your Torn API key immediately invalidates the authentication token.</p>

                <h4>Your Consent</h4>
                <p>By continuing, you acknowledge you understand what a Torn API key is, how Odin Tools uses and stores it, how the authentication process works, and you consent to using your API key for these purposes. If you are uncomfortable at any time, do not proceed, regenerate your Torn API key, or disable/remove Odin Tools.</p>
              </div>
            </div>

            <div class="odin-auth-footer">
              <label class="odin-auth-ack">
                <input type="checkbox" id="odin-auth-ack" />
                I have read and understand how my Torn Full Access API key is used and stored.
              </label>

              <label class="odin-form-label" style="margin-top:8px;">Torn API Key</label>
              <input
                type="password"
                id="odin-auth-torn-key"
                class="odin-input"
                placeholder="${savedMasked ? ('Saved key detected (' + savedMasked + ') - paste to re-auth') : 'Paste your Torn API key'}"
              />

              <div class="odin-auth-actions">
                <button class="odin-btn odin-btn-primary" id="odin-auth-btn" disabled>Authenticate</button>
                <button class="odin-btn odin-btn-secondary" id="odin-auth-use-saved" disabled>Use Saved</button>
              </div>

              <div style="margin-top: 12px; text-align: center;">
                <button class="odin-btn odin-btn-secondary" id="odin-auth-later" style="width: 100%;">Authenticate Later (Local Mode)</button>
              </div>

              <div id="odin-auth-msg" class="odin-auth-msg"></div>
            </div>
          </div>
        </div>`;
    }

    function attachAuthGateHandlers(tabId) {
      const msg = document.getElementById('odin-auth-msg');
      const input = document.getElementById('odin-auth-torn-key');
      const btn = document.getElementById('odin-auth-btn');
      const useSaved = document.getElementById('odin-auth-use-saved');
      const authLater = document.getElementById('odin-auth-later');
      const ack = document.getElementById('odin-auth-ack');

      const ackKey = 'odin_auth_ack_v1';
      const localModeKey = 'odin_local_mode_v1';

      function setMsg(t, kind) {
        if (!msg) return;
        msg.textContent = t || '';
        msg.style.color = kind === 'error' ? '#ff6b6b' : (kind === 'success' ? '#2ecc71' : '#a0a0a0');
      }

      function setEnabled(el, on) {
        if (!el) return;
        el.disabled = !on;
        el.classList.toggle('odin-disabled', !on);
      }

      if (ack && storage && typeof storage.getJSON === 'function') {
        const prior = storage.getJSON(ackKey);
        if (prior === true) ack.checked = true;
      }

      function applyAckState() {
        const ok = !!(ack && ack.checked);
        setEnabled(btn, ok);
        setEnabled(useSaved, ok);

        if (!ok) {
          setMsg('Please read the notice and acknowledge it to enable authentication.', 'info');
        } else if (msg && msg.textContent && msg.textContent.indexOf('acknowledge') !== -1) {
          setMsg('', 'info');
        }

        if (storage && typeof storage.setJSON === 'function') storage.setJSON(ackKey, ok);
      }

      if (ack) ack.addEventListener('change', applyAckState, { passive: true });
      applyAckState();

      if (useSaved) {
        useSaved.onclick = () => {
          const saved = getSavedTornKey();
          if (input) input.value = saved || '';
          setMsg(saved ? 'Loaded saved key into the field.' : 'No saved key found. Paste a key to continue.', saved ? 'success' : 'error');
        };
      }

      if (authLater) {
        authLater.onclick = () => {
          if (storage && typeof storage.setJSON === 'function') {
            storage.setJSON(localModeKey, true);
          }
          setMsg('Local mode enabled. Database features will be unavailable.', 'info');
          setTimeout(() => {
            renderTabContent(tabId);
          }, 500);
        };
      }

      if (btn) {
        btn.onclick = async () => {
          try {
            const ok = !!(ack && ack.checked);
            if (!ok) {
              setMsg('Please acknowledge the notice before authenticating.', 'error');
              return;
            }

            setMsg('Authenticating...', 'info');
            const key = (input && input.value) ? input.value.trim() : '';
            if (!key || key.length < 16) {
              setMsg('Please paste a valid Torn API key.', 'error');
              return;
            }

            // Save for future Torn API calls (single entry flow)
            try {
              if (ctx.api && typeof ctx.api.setTornApiKey === 'function') {
                ctx.api.setTornApiKey(key, { persist: true, silent: true });
              }
            } catch (_) {}

            if (!ctx.firebase || typeof ctx.firebase.authenticateWithTorn !== 'function') {
              setMsg('Firebase service is not ready yet. Try again in a moment.', 'error');
              return;
            }

            await ctx.firebase.authenticateWithTorn(key);

            // Get authenticated user info
            const currentUser = ctx.firebase.getCurrentUser && ctx.firebase.getCurrentUser();
            authUserPresent = !!currentUser;

            // Show success message with user details
            const userId = currentUser?.uid || 'Unknown';
            setMsg('✓ Authentication successful! User ID: ' + userId + ' - Loading...', 'success');

            // Wait a moment to show success message
            setTimeout(() => {
              renderTabContent(tabId);
            }, 800);
          } catch (e) {
            setMsg('Authentication failed: ' + (e && e.message ? e.message : String(e)), 'error');
          }
        };
      }
    }

    // ============================================
    // STYLES
    // ============================================
    function injectStyles() {
      if (document.getElementById('odin-ui-styles')) return;

      const styles = document.createElement('style');
      styles.id = 'odin-ui-styles';

      styles.textContent = `
        /* Overlay/Backdrop */
        #odin-overlay {
          position: fixed;
          inset: 0;
          background: rgba(0, 0, 0, 0.5);
          z-index: 99997;
          display: none;
          backdrop-filter: blur(2px);
          transition: opacity 0.3s ease;
        }
        #odin-overlay.visible {
          display: block;
        }

        /* Toggle Button */
        #odin-toggle-btn {
          position: fixed;
          bottom: 20px;
          left: 20px;
          width: 48px;
          height: 48px;
          border-radius: 50%;
          background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
          border: 2px solid #8B0000;
          cursor: pointer;
          z-index: 99999;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 0;
          box-shadow: 0 4px 15px rgba(139, 0, 0, 0.4);
          transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
          animation: pulse-glow 2s ease-in-out infinite;
        }
        #odin-toggle-btn:hover {
          transform: scale(1.15) rotate(5deg);
          box-shadow: 0 8px 30px rgba(139, 0, 0, 0.7);
          animation: none;
        }
        #odin-toggle-btn:active {
          transform: scale(0.95);
        }
        #odin-toggle-btn.active {
          background: linear-gradient(135deg, #8B0000 0%, #6B0000 100%);
          z-index: 99996;
          animation: none;
        }
        @keyframes pulse-glow {
          0%, 100% {
            box-shadow: 0 4px 15px rgba(139, 0, 0, 0.4);
          }
          50% {
            box-shadow: 0 4px 25px rgba(139, 0, 0, 0.6);
          }
        }

        /* Main Panel */
        #odin-panel {
          position: fixed;
          top: 60px;
          right: 20px;
          width: 440px;
          max-width: calc(100vw - 40px);
          max-height: calc(100vh - 100px);
          background: linear-gradient(180deg, #1a1a2e 0%, #0f0f1a 100%);
          border: 1px solid #8B0000;
          border-radius: 12px;
          z-index: 99998;
          display: none;
          flex-direction: column;
          box-shadow: 0 10px 40px rgba(0, 0, 0, 0.5);
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }
        #odin-panel.visible { display: flex; }

        /* Drag Bar */
        .odin-drag-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 8px 12px;
          background: linear-gradient(90deg, #1a0a0a 0%, #2a0a0a 100%);
          border-bottom: 1px solid rgba(139, 0, 0, 0.5);
          border-radius: 11px 11px 0 0;
          cursor: move;
          user-select: none;
        }
        .odin-drag-bar-title {
          color: #8B0000;
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.5px;
          text-transform: uppercase;
        }
        .odin-drag-bar-close {
          width: 24px;
          height: 24px;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          border-radius: 4px;
          color: #8B0000;
          font-size: 16px;
          font-weight: 700;
          transition: all 0.2s ease;
        }
        .odin-drag-bar-close:hover {
          background: rgba(139, 0, 0, 0.2);
          transform: scale(1.1);
        }

        /* Header */
        .odin-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px 16px;
          background: linear-gradient(90deg, #16213e 0%, #1a1a2e 100%);
          border-bottom: 1px solid #8B0000;
        }
        .odin-header-title {
          display: flex;
          align-items: center;
          gap: 10px;
          color: #fff;
          font-size: 18px;
          font-weight: 600;
        }
        .odin-header-status {
          display: flex;
          align-items: center;
          gap: 8px;
        }
        .odin-status-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
          background: #4ade80;
        }
        .odin-status-dot.offline { background: #ef4444; }
        .odin-status-dot.connecting { background: #fbbf24; animation: pulse 1s infinite; }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }

        /* Tab Navigation */
        .odin-tabs {
          display: flex;
          flex-wrap: nowrap;
          overflow-x: auto;
          gap: 4px;
          padding: 8px;
          background: #16213e;
          border-bottom: 1px solid rgba(139, 0, 0, 0.3);
        }
        .odin-tab {
          flex: 0 0 auto;
          white-space: nowrap;
          min-width: 70px;
          padding: 8px 10px;
          background: transparent;
          border: 1px solid transparent;
          border-radius: 6px;
          color: #a0a0a0;
          font-size: 11px;
          cursor: pointer;
          transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
          text-align: center;
          position: relative;
          overflow: hidden;
        }
        .odin-tab::before {
          content: '';
          position: absolute;
          bottom: 0;
          left: 50%;
          width: 0;
          height: 2px;
          background: #8B0000;
          transform: translateX(-50%);
          transition: width 0.3s ease;
        }
        .odin-tab:hover {
          background: rgba(139, 0, 0, 0.1);
          color: #fff;
          transform: translateY(-2px);
        }
        .odin-tab:hover::before {
          width: 80%;
        }
        .odin-tab:active {
          transform: translateY(0) scale(0.95);
        }
        .odin-tab.active {
          background: linear-gradient(135deg, #8B0000 0%, #6B0000 100%);
          color: #fff;
          border-color: #8B0000;
          box-shadow: 0 2px 8px rgba(139, 0, 0, 0.4);
          transform: translateY(0);
        }
        .odin-tab.active::before {
          width: 100%;
          height: 100%;
          background: rgba(255, 255, 255, 0.1);
          border-radius: 6px;
        }

        /* Content Area */
        .odin-content {
          flex: 1;
          overflow-y: auto;
          padding: 16px;
          color: #e0e0e0;
          max-height: 550px;
          animation: fadeIn 0.3s ease-in-out;
        }
        .odin-content::-webkit-scrollbar { width: 6px; }
        .odin-content::-webkit-scrollbar-track { background: #1a1a2e; }
        .odin-content::-webkit-scrollbar-thumb { background: #8B0000; border-radius: 3px; }
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        /* ============================
           AUTH TERMINAL SCREEN
           ============================ */
        .odin-content.odin-content-auth {
          display: flex;
          flex-direction: column;
          height: 500px;
          overflow: hidden !important;
        }
        .odin-content.odin-content-auth > .odin-card.odin-auth-card {
          flex: 1 1 auto;
          display: flex;
          flex-direction: column;
          min-height: 0;
        }
        .odin-content.odin-content-auth > .odin-card.odin-auth-card .odin-card-header { flex: 0 0 auto; }
        .odin-content.odin-content-auth > .odin-card.odin-auth-card .odin-auth-shell {
          flex: 1 1 auto;
          display: flex;
          flex-direction: column;
          min-height: 0;
          gap: 10px;
        }
        .odin-auth-info { flex: 0 0 auto; padding: 2px 0 0 0; }
        .odin-auth-info-line { margin-bottom: 8px; }
        .odin-auth-status { color: #a0a0a0; font-size: 12px; }

        /* "Data terminal" screen box */
        .odin-auth-scroll {
          flex: 1 1 auto;
          min-height: 0;
          overflow-y: auto;
          position: relative;

          border: 1px solid #8B0000;
          border-radius: 12px;

          background: #05050a;
          box-shadow: 0 0 10px rgba(139, 0, 0, 0.4);

          padding: 12px;

          font-family: "Courier New", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
          letter-spacing: 0.2px;
          color: #eaeaea;
          text-shadow: 0 0 6px rgba(139, 0, 0, 0.10);
        }

        /* Scanlines + subtle vignette overlay */
        .odin-auth-scroll::before {
          content: "";
          position: absolute;
          inset: 0;
          pointer-events: none;
          background:
            radial-gradient(120% 90% at 50% 20%, rgba(139, 0, 0, 0.08), rgba(5, 5, 10, 0.0) 60%),
            repeating-linear-gradient(
              to bottom,
              rgba(139, 0, 0, 0.08) 0px,
              rgba(139, 0, 0, 0.02) 1px,
              rgba(5, 5, 10, 0.00) 2px,
              rgba(5, 5, 10, 0.00) 4px
            );
          opacity: 0.40;
        }
        .odin-auth-scroll > * { position: relative; z-index: 1; }

        .odin-auth-scroll::-webkit-scrollbar { width: 6px; }
        .odin-auth-scroll::-webkit-scrollbar-track { background: rgba(5, 5, 10, 0.85); }
        .odin-auth-scroll::-webkit-scrollbar-thumb { background: rgba(139, 0, 0, 0.85); border-radius: 3px; }

        .odin-auth-disclaimer-title {
          font-weight: 800;
          color: #ffffff;
          font-size: 13px;
          margin-bottom: 10px;
        }
        .odin-auth-disclaimer-body h4 {
          margin: 12px 0 6px 0;
          font-size: 12px;
          color: #ffffff;
        }
        .odin-auth-disclaimer-body p {
          margin: 0 0 10px 0;
          font-size: 12px;
          color: #d8d8d8;
          line-height: 1.35;
        }
        .odin-auth-disclaimer-body code {
          background: rgba(139, 0, 0, 0.10);
          border: 1px solid rgba(139, 0, 0, 0.25);
          padding: 1px 6px;
          border-radius: 6px;
          font-size: 11px;
          color: #fff;
        }

        .odin-auth-footer {
          flex: 0 0 auto;
          padding-top: 8px;
          border-top: 1px solid rgba(139, 0, 0, 0.18);
        }

        .odin-auth-ack {
          display: flex;
          gap: 10px;
          align-items: flex-start;
          font-size: 12px;
          color: #d6d6d6;
          line-height: 1.25;
          user-select: none;
        }
        .odin-auth-ack input {
          width: 18px;
          height: 18px;
          margin-top: 1px;
          flex: 0 0 auto;
        }
        .odin-auth-actions { display: flex; gap: 8px; margin-top: 10px; }
        .odin-auth-actions .odin-btn { flex: 1 1 0; min-height: 44px; }
        .odin-auth-msg { margin-top: 10px; font-size: 12px; color: #a0a0a0; }

        @media (max-width: 768px) {
          .odin-content.odin-content-auth { height: 520px; }
          .odin-auth-scroll { padding: 10px; }
          .odin-auth-disclaimer-body p { font-size: 12px; }
          .odin-auth-actions .odin-btn { min-height: 48px; }
        }

        /* Common Components */
        .odin-card {
          background: rgba(22, 33, 62, 0.8);
          border: 1px solid rgba(139, 0, 0, 0.2);
          border-radius: 8px;
          padding: 12px;
          margin-bottom: 12px;
        }
        .odin-card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;
        }
        .odin-card-title { color: #fff; font-size: 14px; font-weight: 600; }

        .odin-badge {
          display: inline-block;
          padding: 2px 8px;
          border-radius: 12px;
          font-size: 11px;
          font-weight: 500;
        }
        .odin-badge.success { background: #22c55e; color: #fff; }
        .odin-badge.warning { background: #f59e0b; color: #000; }
        .odin-badge.danger { background: #ef4444; color: #fff; }
        .odin-badge.info { background: #3b82f6; color: #fff; }
        .odin-badge.neutral { background: #6b7280; color: #fff; }

        .odin-btn {
          padding: 8px 16px;
          border-radius: 6px;
          border: none;
          cursor: pointer;
          font-size: 13px;
          font-weight: 500;
          transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
          position: relative;
          overflow: hidden;
        }
        .odin-btn::before {
          content: '';
          position: absolute;
          top: 50%;
          left: 50%;
          width: 0;
          height: 0;
          border-radius: 50%;
          background: rgba(255, 255, 255, 0.3);
          transform: translate(-50%, -50%);
          transition: width 0.6s, height 0.6s;
        }
        .odin-btn:active::before {
          width: 300px;
          height: 300px;
        }
        .odin-btn-primary {
          background: linear-gradient(135deg, #8B0000 0%, #6B0000 100%);
          color: #fff;
          box-shadow: 0 2px 8px rgba(139, 0, 0, 0.3);
        }
        .odin-btn-primary:hover {
          transform: translateY(-2px) scale(1.02);
          box-shadow: 0 6px 16px rgba(139, 0, 0, 0.5);
        }
        .odin-btn-primary:active {
          transform: translateY(0) scale(0.98);
        }
        .odin-btn-secondary {
          background: rgba(255, 255, 255, 0.1);
          color: #e0e0e0;
          border: 1px solid rgba(255, 255, 255, 0.2);
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }
        .odin-btn-secondary:hover {
          background: rgba(255, 255, 255, 0.15);
          transform: translateY(-2px);
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
        }
        .odin-btn-secondary:active {
          transform: translateY(0) scale(0.98);
        }
        .odin-btn-small { padding: 4px 10px; font-size: 11px; }
        .odin-btn-success {
          background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
          color: #fff;
          box-shadow: 0 2px 8px rgba(34, 197, 94, 0.3);
        }
        .odin-btn-success:hover {
          transform: translateY(-2px) scale(1.02);
          box-shadow: 0 6px 16px rgba(34, 197, 94, 0.5);
        }
        .odin-btn-success:active {
          transform: translateY(0) scale(0.98);
        }
        .odin-btn-danger {
          background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
          color: #fff;
          box-shadow: 0 2px 8px rgba(239, 68, 68, 0.3);
        }
        .odin-btn-danger:hover {
          transform: translateY(-2px) scale(1.02);
          box-shadow: 0 6px 16px rgba(239, 68, 68, 0.5);
        }
        .odin-btn-danger:active {
          transform: translateY(0) scale(0.98);
        }
        .odin-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
          transform: none !important;
        }

        /* Form Elements */
        .odin-form-group { margin-bottom: 16px; }
        .odin-form-label {
          display: block;
          color: #a0a0a0;
          font-size: 12px;
          margin-bottom: 6px;
        }
        .odin-input {
          width: 100%;
          padding: 10px 12px;
          background: rgba(0, 0, 0, 0.3);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 6px;
          color: #fff;
          font-size: 13px;
          box-sizing: border-box;
        }
        .odin-input:focus { outline: none; border-color: #8B0000; }

        .odin-checkbox-group {
          display: flex;
          align-items: center;
          gap: 8px;
          margin-bottom: 12px;
        }
        .odin-checkbox-group input[type="checkbox"] {
          width: 16px;
          height: 16px;
          accent-color: #8B0000;
        }
        .odin-checkbox-group label { color: #e0e0e0; font-size: 13px; }

        .odin-select {
          width: 100%;
          padding: 10px 12px;
          background: rgba(0, 0, 0, 0.3);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 6px;
          color: #fff;
          font-size: 13px;
        }

        /* Stats Grid */
        .odin-stats-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 12px;
          margin-bottom: 16px;
        }
        .odin-stat-item {
          text-align: center;
          padding: 12px;
          background: rgba(0, 0, 0, 0.2);
          border-radius: 8px;
        }
        .odin-stat-value { font-size: 24px; font-weight: 700; color: #8B0000; }
        .odin-stat-label { font-size: 11px; color: #a0a0a0; margin-top: 4px; }

        /* Target List */
        .odin-target-item {
          display: flex;
          align-items: center;
          padding: 10px;
          background: rgba(0, 0, 0, 0.2);
          border-radius: 6px;
          margin-bottom: 8px;
        }
        .odin-target-item.claimed { border-left: 3px solid #f59e0b; }
        .odin-score {
          width: 36px;
          height: 36px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 700;
          font-size: 12px;
        }
        .odin-score.high { background: #22c55e; color: #fff; }
        .odin-score.medium { background: #f59e0b; color: #000; }
        .odin-score.low { background: #ef4444; color: #fff; }
        .odin-target-info { flex: 1; margin-left: 12px; }
        .odin-target-name a { color: #60a5fa; text-decoration: none; }
        .odin-target-name a:hover { text-decoration: underline; }
        .odin-target-meta { font-size: 11px; color: #a0a0a0; margin-top: 2px; }
        .odin-target-actions { display: flex; gap: 6px; }

        /* Empty State */
        .odin-empty { text-align: center; padding: 40px 20px; color: #6b7280; }
        .odin-empty-icon { font-size: 48px; margin-bottom: 12px; }

        /* Toast */
        .odin-toast {
          position: fixed;
          top: 20px;
          left: 50%;
          transform: translateX(-50%);
          padding: 14px 24px;
          border-radius: 8px;
          color: #fff;
          font-size: 14px;
          font-weight: 500;
          z-index: 999999;
          animation: slideDown 0.4s cubic-bezier(0.4, 0, 0.2, 1);
          box-shadow: 0 10px 40px rgba(0, 0, 0, 0.3);
          min-width: 300px;
          text-align: center;
        }
        .odin-toast.success {
          background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
          border: 1px solid rgba(255, 255, 255, 0.2);
        }
        .odin-toast.error {
          background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
          border: 1px solid rgba(255, 255, 255, 0.2);
        }
        .odin-toast.warning {
          background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
          color: #fff;
          border: 1px solid rgba(255, 255, 255, 0.2);
        }
        .odin-toast.info {
          background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
          border: 1px solid rgba(255, 255, 255, 0.2);
        }
        @keyframes slideDown {
          from {
            transform: translateX(-50%) translateY(-100%);
            opacity: 0;
          }
          to {
            transform: translateX(-50%) translateY(0);
            opacity: 1;
          }
        }

        /* Chain Timer */
        .odin-chain-timer { font-size: 48px; font-weight: 700; text-align: center; padding: 20px; }
        .odin-chain-timer.safe { color: #22c55e; }
        .odin-chain-timer.warning { color: #f59e0b; }
        .odin-chain-timer.danger { color: #ef4444; }

        /* Schedule Grid */
        .odin-schedule-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 4px; }
        .odin-schedule-slot {
          padding: 8px 4px;
          text-align: center;
          background: rgba(0, 0, 0, 0.2);
          border-radius: 4px;
          font-size: 10px;
          cursor: pointer;
        }
        .odin-schedule-slot.filled { background: rgba(34, 197, 94, 0.3); }
        .odin-schedule-slot.empty { background: rgba(239, 68, 68, 0.3); }
        .odin-schedule-slot.mine { background: rgba(59, 130, 246, 0.3); }

        /* Heatmap */
        .odin-heatmap { display: grid; grid-template-columns: 20px repeat(24, 1fr); gap: 2px; }
        .odin-heatmap-label { font-size: 9px; color: #6b7280; text-align: center; }
        .odin-heatmap-cell { height: 12px; border-radius: 2px; }

        /* Member List */
        .odin-member-item {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 8px;
          background: rgba(0, 0, 0, 0.2);
          border-radius: 6px;
          margin-bottom: 6px;
        }
        .odin-member-name { color: #60a5fa; font-size: 13px; }
        .odin-member-status { font-size: 11px; }

        /* Log Console */
        .odin-log-console {
          max-height: 400px;
          overflow-y: auto;
          background: rgba(0, 0, 0, 0.4);
          border: 1px solid rgba(139, 0, 0, 0.2);
          border-radius: 6px;
          padding: 8px;
          font-family: 'Courier New', monospace;
          font-size: 11px;
        }
        .odin-log-console::-webkit-scrollbar { width: 6px; }
        .odin-log-console::-webkit-scrollbar-track { background: #1a1a2e; }
        .odin-log-console::-webkit-scrollbar-thumb { background: #8B0000; border-radius: 3px; }

        .odin-log-entry {
          padding: 4px 6px;
          margin-bottom: 2px;
          border-left: 3px solid transparent;
          border-radius: 3px;
          display: flex;
          gap: 8px;
          align-items: flex-start;
        }
        .odin-log-entry.log-error {
          background: rgba(239, 68, 68, 0.1);
          border-left-color: #ef4444;
        }
        .odin-log-entry.log-api {
          background: rgba(59, 130, 246, 0.1);
          border-left-color: #3b82f6;
        }
        .odin-log-entry.log-db {
          background: rgba(245, 158, 11, 0.1);
          border-left-color: #f59e0b;
        }
        .odin-log-entry.log-network {
          background: rgba(34, 197, 94, 0.1);
          border-left-color: #22c55e;
        }
        .odin-log-entry.log-event {
          background: rgba(168, 85, 247, 0.1);
          border-left-color: #a855f7;
        }
        .odin-log-time {
          color: #6b7280;
          min-width: 70px;
          flex-shrink: 0;
        }
        .odin-log-type {
          color: #8B0000;
          min-width: 100px;
          flex-shrink: 0;
          text-transform: uppercase;
          font-weight: 600;
        }
        .odin-log-content {
          color: #e0e0e0;
          flex: 1;
          word-break: break-word;
        }
        .odin-log-content a {
          color: #60a5fa;
          text-decoration: underline;
        }
        .odin-log-content a:hover {
          color: #93c5fd;
        }
      `;

      document.head.appendChild(styles);
    }

    // ============================================
    // CREATE UI ELEMENTS
    // ============================================
    function createToggleButton() {
      toggleButton = document.createElement('button');
      toggleButton.id = 'odin-toggle-btn';
      toggleButton.innerHTML = '<img src="https://i.postimg.cc/BQ6bSYKM/file-000000004bb071f5a96fc52564bf26ad-(1).png" alt="Odin" style="width:28px;height:28px;display:block;" />';
      toggleButton.title = 'Odin Faction Tools';
      toggleButton.onclick = togglePanel;
      document.body.appendChild(toggleButton);
    }

    function createPanel() {
      // Create overlay/backdrop
      const overlay = document.createElement('div');
      overlay.id = 'odin-overlay';
      overlay.onclick = hidePanel;
      document.body.appendChild(overlay);

      panelElement = document.createElement('div');
      panelElement.id = 'odin-panel';

      const connectionStatus = firebaseConnected ? 'connected' : 'connecting';

      panelElement.innerHTML = `
        <div class="odin-drag-bar" id="odin-drag-bar">
          <div class="odin-drag-bar-title">Odin Faction Tools</div>
          <div class="odin-drag-bar-close" id="odin-close-btn" title="Close">✕</div>
        </div>

        <div class="odin-header">
          <div class="odin-header-title">
            <img src="https://i.postimg.cc/BQ6bSYKM/file-000000004bb071f5a96fc52564bf26ad-(1).png" alt="Odin" style="width:22px;height:22px;display:block;" />
            <span>Odin Tools</span>
          </div>
          <div class="odin-header-status">
            <div id="odin-status-dot" class="odin-status-dot ${connectionStatus === 'connected' ? '' : 'connecting'}"></div>
            <span id="odin-status-text" style="color: #a0a0a0; font-size: 11px;">
              ${connectionStatus === 'connected' ? 'Online' : 'Connecting...'}
            </span>
          </div>
        </div>

        <div class="odin-tabs">
          ${Object.entries(tabs).map(([id, tab]) => `
            <button class="odin-tab ${id === activeTab ? 'active' : ''}" data-tab="${id}">
              ${tab.label}
            </button>
          `).join('')}
        </div>

        <div class="odin-content" id="odin-tab-content">
          <!-- Content injected dynamically -->
        </div>
      `;

      // Tab click handlers
      panelElement.querySelectorAll('.odin-tab').forEach(tab => {
        tab.onclick = () => switchTab(tab.dataset.tab);
      });

      document.body.appendChild(panelElement);

      // Close button handler
      const closeBtn = document.getElementById('odin-close-btn');
      if (closeBtn) {
        closeBtn.onclick = (e) => {
          e.stopPropagation();
          hidePanel();
        };
      }

      // Drag functionality
      const dragBar = document.getElementById('odin-drag-bar');
      if (dragBar) {
        let isDragging = false;
        let currentX = 0;
        let currentY = 0;
        let initialX = 0;
        let initialY = 0;

        dragBar.addEventListener('mousedown', (e) => {
          // Don't drag if clicking the close button
          if (e.target.id === 'odin-close-btn' || e.target.closest('#odin-close-btn')) {
            return;
          }

          isDragging = true;
          const rect = panelElement.getBoundingClientRect();
          initialX = e.clientX - rect.left;
          initialY = e.clientY - rect.top;

          dragBar.style.cursor = 'grabbing';
        });

        document.addEventListener('mousemove', (e) => {
          if (!isDragging) return;

          e.preventDefault();
          currentX = e.clientX - initialX;
          currentY = e.clientY - initialY;

          // Keep panel within viewport
          const maxX = window.innerWidth - panelElement.offsetWidth;
          const maxY = window.innerHeight - panelElement.offsetHeight;

          currentX = Math.max(0, Math.min(currentX, maxX));
          currentY = Math.max(0, Math.min(currentY, maxY));

          panelElement.style.right = 'auto';
          panelElement.style.top = currentY + 'px';
          panelElement.style.left = currentX + 'px';
        });

        document.addEventListener('mouseup', () => {
          if (isDragging) {
            isDragging = false;
            dragBar.style.cursor = 'move';
          }
        });
      }

      renderTabContent(activeTab);
    }

    function switchTab(tabId) {
      activeTab = tabId;
      panelElement.querySelectorAll('.odin-tab').forEach(tab => {
        tab.classList.toggle('active', tab.dataset.tab === tabId);
      });
      renderTabContent(tabId);
    }

    // ============================================
    // TAB RENDERERS
    // ============================================
    function renderTabContent(tabId) {
      const container = document.getElementById('odin-tab-content');
      if (!container) return;

      const needsAuthGate = AUTH_REQUIRED_TABS.has(tabId) && !isAuthReady();
      container.classList.toggle('odin-content-auth', needsAuthGate);

      // Guard data-sensitive tabs until Firebase is connected AND auth user exists
      if (needsAuthGate) {
        container.innerHTML = renderAuthGate(tabId);
        attachAuthGateHandlers(tabId);
        return;
      }

      switch (tabId) {
        case 'warRoom':
          container.innerHTML = renderWarRoomTab();
          break;
        case 'targets':
          container.innerHTML = renderTargetsTab();
          break;
        case 'chain':
          container.innerHTML = renderChainTab();
          break;
        case 'schedule':
          container.innerHTML = renderScheduleTab();
          break;
        case 'leadership':
          container.innerHTML = renderLeadershipTab();
          break;
        case 'personal':
          container.innerHTML = renderPersonalTab();
          break;
        case 'settings':
          container.innerHTML = renderSettingsTab();
          attachSettingsHandlers();
          break;
        default:
          container.innerHTML = '<div class="odin-empty">Tab not found</div>';
      }
    }

    function renderWarRoomTab() {
      const state = ctx.spear?.getState?.() || {};
      const claims = state.claims || {};
      const dibs = state.dibs || {};
      const chain = state.chain || {};
      const presence = state.presence || {};

      const activeClaims = Object.values(claims).filter(c => c.status === 'active').length;
      const activeDibs = Object.values(dibs).filter(d => d.status === 'active').length;
      const onlineMembers = Object.values(presence).filter(p => p.status === 'online').length;

      return `
        <div class="odin-stats-grid">
          <div class="odin-stat-item">
            <div class="odin-stat-value">${activeClaims}</div>
            <div class="odin-stat-label">Active Claims</div>
          </div>
          <div class="odin-stat-item">
            <div class="odin-stat-value">${activeDibs}</div>
            <div class="odin-stat-label">Active Dibs</div>
          </div>
          <div class="odin-stat-item">
            <div class="odin-stat-value">${onlineMembers}</div>
            <div class="odin-stat-label">Online</div>
          </div>
          <div class="odin-stat-item">
            <div class="odin-stat-value">${chain.current || 0}</div>
            <div class="odin-stat-label">Chain</div>
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">⚡ Quick Actions</div>
          </div>
          <div style="display: flex; gap: 8px; flex-wrap: wrap;">
            <button class="odin-btn odin-btn-primary" onclick="window.OdinUI.refreshClaims()">
              🔄 Refresh
            </button>
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.scoreAllTargets()">
              🎯 Score Targets
            </button>
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.startWatching()">
              👁️ Watch Mode
            </button>
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">📋 Recent Activity</div>
          </div>
          <div style="font-size: 12px; color: #a0a0a0;">
            ${renderRecentActivity()}
          </div>
        </div>
      `;
    }

    function renderTargetsTab() {
      const state = ctx.spear?.getState?.() || {};
      const targets = state.targets || {};
      const claims = state.claims || {};

      return `
        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">➕ Add Target</div>
          </div>
          <div style="display: flex; gap: 8px;">
            <input type="text" id="odin-add-target-input" class="odin-input"
                    placeholder="Player ID or profile URL" style="flex: 1;">
            <button class="odin-btn odin-btn-primary" onclick="window.OdinUI.addTarget()">
              Add
            </button>
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">🎯 Faction Targets</div>
            <span class="odin-badge info">${Object.keys(targets).length}</span>
          </div>
          ${renderTargetList(targets, claims)}
        </div>
      `;
    }

    function renderChainTab() {
      const state = ctx.spear?.getState?.() || {};
      const chain = state.chain || {};
      const timeout = chain.timeout || 0;
      const timerClass = getChainTimerClass(timeout);

      return `
        <div class="odin-card">
          <div class="odin-chain-timer ${timerClass}">
            ${formatChainTimer(timeout)}
          </div>
          <div style="text-align: center; margin-bottom: 16px;">
            <span style="font-size: 24px; font-weight: 600; color: #fff;">
              ${chain.current || 0}
            </span>
            <span style="color: #6b7280;"> / ${chain.max || 0}</span>
          </div>
          <div style="display: flex; justify-content: center; gap: 8px;">
            <button class="odin-btn odin-btn-danger" onclick="window.OdinUI.alertChain()">
              🚨 Alert
            </button>
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.refreshClaims()">
              🔄 Refresh
            </button>
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">📊 Chain Stats</div>
          </div>
          <div class="odin-stats-grid">
            <div class="odin-stat-item">
              <div class="odin-stat-value">${chain.hitsToday || 0}</div>
              <div class="odin-stat-label">Hits Today</div>
            </div>
            <div class="odin-stat-item">
              <div class="odin-stat-value">${chain.respectEarned || 0}</div>
              <div class="odin-stat-label">Respect</div>
            </div>
          </div>
        </div>
      `;
    }

    function renderScheduleTab() {
      const state = ctx.spear?.getState?.() || {};
      const schedule = state.watcherSchedule || {};
      const myId = ctx.userId;

      return `
        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">📅 Watcher Schedule</div>
          </div>
          <div class="odin-schedule-grid">
            ${renderScheduleGrid(schedule, myId)}
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">✏️ Sign Up for Slot</div>
          </div>

          <div class="odin-form-group">
            <label class="odin-form-label">Select Day</label>
            <select id="odin-schedule-day" class="odin-select">
              <option value="0">Sunday</option>
              <option value="1">Monday</option>
              <option value="2">Tuesday</option>
              <option value="3">Wednesday</option>
              <option value="4">Thursday</option>
              <option value="5">Friday</option>
              <option value="6">Saturday</option>
            </select>
          </div>

          <div class="odin-form-group">
            <label class="odin-form-label">Select Hour</label>
            <select id="odin-schedule-hour" class="odin-select">
              ${Array.from({length: 24}, (_, i) =>
                `<option value="${i}">${String(i).padStart(2, '0')}:00</option>`
              ).join('')}
            </select>
          </div>

          <button class="odin-btn odin-btn-primary" onclick="window.OdinUI.signUpForSlot()">
            Sign Up
          </button>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">🔥 Activity Heatmap</div>
          </div>
          <div class="odin-heatmap">
            ${renderHeatmap(schedule.heatmap || {})}
          </div>
        </div>
      `;
    }

    function renderLeadershipTab() {
      const canViewLeadership = ctx.access?.canViewLeadership?.() || false;
      if (!canViewLeadership) {
        return `
          <div class="odin-empty">
            <div class="odin-empty-icon">🔒</div>
            <div>Leadership features require elevated permissions</div>
          </div>
        `;
      }

      // Check if this is dev unlock
      const currentTornId = ctx.store?.get('auth.tornId', null);
      const isDevUnlock = currentTornId === '3666214';

      const state = ctx.spear?.getState?.() || {};
      const members = state.members || {};
      const presence = state.presence || {};

      return `
        ${isDevUnlock ? `
        <div class="odin-card" style="border: 1px solid rgba(139, 0, 0, 0.5);">
          <div style="display: flex; align-items: center; justify-content: center; gap: 8px; padding: 8px;">
            <span style="font-size: 11px; color: #8B0000;">🔧</span>
            <span style="font-size: 11px; color: #e0e0e0;">DEV MODE ACTIVE</span>
            <span style="font-size: 11px; color: #8B0000;">🔧</span>
          </div>
        </div>
        ` : ''}

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">👥 Faction Members</div>
            <span class="odin-badge info">${Object.keys(members).length}</span>
          </div>
          ${renderMemberList(members, presence)}
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">📊 Bulk Operations</div>
          </div>
          <div style="display: flex; gap: 8px; flex-wrap: wrap;">
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.exportData()">
              📤 Export Data
            </button>
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.clearExpired()">
              🧹 Clear Expired
            </button>
          </div>
        </div>
      `;
    }

    function renderPersonalTab() {
      const state = ctx.spear?.getState?.() || {};
      const favorites = state.favorites || {};
      const personalTargets = state.personalTargets || {};
      const frekiInfo = ctx.freki?.getModelInfo?.() || {};

      return `
        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">⭐ Favorites</div>
            <span class="odin-badge info">${Object.keys(favorites).length}</span>
          </div>
          ${renderFavoritesList(favorites)}
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">🎯 Personal Targets</div>
            <span class="odin-badge info">${Object.keys(personalTargets).length}</span>
          </div>
          ${renderPersonalTargetsList(personalTargets)}
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">🧠 Freki AI Stats</div>
          </div>
          <div style="font-size: 12px; color: #a0a0a0;">
            <div>Model Version: ${frekiInfo.version || 'Not loaded'}</div>
            <div>Training Samples: ${frekiInfo.trainingCount || 0}</div>
            <div>Cache Size: ${frekiInfo.cacheSize || 0}</div>
          </div>
          <button class="odin-btn odin-btn-secondary odin-btn-small"
                  onclick="window.OdinUI.getRecommendations()" style="margin-top: 8px;">
            🎲 Get Recommendations
          </button>
        </div>
      `;
    }

    function renderLogConsole() {
      const logManager = ctx.logManager || window.OdinLogManager;
      if (!logManager) {
        return '<div style="color: #6b7280; padding: 10px;">Log manager not initialized</div>';
      }

      const stats = logManager.getLogStats();
      const recentLogs = logManager.getLogs({ limit: 50 });

      return `
        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">📊 Log Statistics</div>
          </div>
          <div class="odin-stats-grid">
            <div class="odin-stat-item">
              <div class="odin-stat-value">${stats.total}</div>
              <div class="odin-stat-label">Total Logs</div>
            </div>
            <div class="odin-stat-item">
              <div class="odin-stat-value">${stats.errors}</div>
              <div class="odin-stat-label">Errors</div>
            </div>
            <div class="odin-stat-item">
              <div class="odin-stat-value">${stats.apiCalls}</div>
              <div class="odin-stat-label">API Calls</div>
            </div>
            <div class="odin-stat-item">
              <div class="odin-stat-value">${stats.databaseCalls}</div>
              <div class="odin-stat-label">DB Calls</div>
            </div>
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">🔍 Filter Logs</div>
          </div>
          <div class="odin-form-group">
            <label class="odin-form-label">Log Type</label>
            <select id="odin-log-filter-type" class="odin-select">
              <option value="all">All Logs</option>
              <option value="errors">Errors Only</option>
              <option value="apiCalls">API Calls</option>
              <option value="databaseCalls">Database Calls</option>
              <option value="networkCalls">Network Calls</option>
              <option value="events">Events</option>
            </select>
          </div>
          <div class="odin-form-group">
            <label class="odin-form-label">Search</label>
            <input type="text" id="odin-log-search" class="odin-input" placeholder="Search logs...">
          </div>
          <div style="display: flex; gap: 8px; margin-top: 10px;">
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.filterLogs()">
              🔍 Filter
            </button>
            <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.refreshLogs()">
              🔄 Refresh
            </button>
          </div>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">📋 Log Console</div>
            <div style="display: flex; gap: 6px;">
              <button class="odin-btn odin-btn-small odin-btn-secondary" onclick="window.OdinUI.copyLogs()">
                📋 Copy
              </button>
              <button class="odin-btn odin-btn-small odin-btn-primary" onclick="window.OdinUI.sendLogsToBjorn()">
                📧 Send to Bjorn
              </button>
              <button class="odin-btn odin-btn-small odin-btn-danger" onclick="window.OdinUI.clearLogs()">
                🗑️ Clear
              </button>
            </div>
          </div>
          <div id="odin-log-console" class="odin-log-console">
            ${renderLogEntries(recentLogs)}
          </div>
        </div>
      `;
    }

    function renderLogEntries(logs) {
      if (!logs || logs.length === 0) {
        return '<div style="color: #6b7280; padding: 10px; text-align: center;">No logs to display</div>';
      }

      return logs.map(entry => {
        const timestamp = new Date(entry.timestamp).toLocaleTimeString();
        const typeClass = entry.type === 'errors' ? 'log-error' :
                         entry.type === 'apiCalls' ? 'log-api' :
                         entry.type === 'databaseCalls' ? 'log-db' :
                         entry.type === 'networkCalls' ? 'log-network' : 'log-event';

        let content = '';
        switch (entry.type) {
          case 'errors':
            content = `<strong>${entry.message}</strong>`;
            break;
          case 'apiCalls':
            const apiUrl = entry.url || `${entry.service}/${entry.endpoint}`;
            const apiLink = entry.url && entry.url.startsWith('http')
              ? `<a href="${entry.url}" target="_blank" style="color: #60a5fa;">${apiUrl}</a>`
              : apiUrl;
            content = `${entry.method || 'GET'} ${apiLink} - ${entry.status} (${entry.duration || 0}ms)`;
            break;
          case 'databaseCalls':
            content = `${entry.operation} ${entry.path} [${entry.direction}] - ${entry.status} (${entry.duration || 0}ms)`;
            break;
          case 'networkCalls':
            const netLink = entry.url && entry.url.startsWith('http')
              ? `<a href="${entry.url}" target="_blank" style="color: #60a5fa;">${entry.url}</a>`
              : entry.url;
            content = `${entry.method} ${netLink} [${entry.direction}] - ${entry.status}`;
            break;
          default:
            content = JSON.stringify(entry.data || {});
        }

        return `
          <div class="odin-log-entry ${typeClass}">
            <span class="odin-log-time">${timestamp}</span>
            <span class="odin-log-type">[${entry.type}]</span>
            <span class="odin-log-content">${content}</span>
          </div>
        `;
      }).join('');
    }

    function renderSettingsTab() {
      const settings = ctx.settings || {};
      const tornKeyExists = !!(ctx.api?.getTornApiKey?.() && String(ctx.api.getTornApiKey()).length > 8);
      const tornStatsKeyExists = !!(ctx.api?.hasTornStatsKey?.());
      const ffScouterKeyExists = !!(ctx.api?.hasFFScouterKey?.());
      const localMode = storage && typeof storage.getJSON === 'function' ? storage.getJSON('odin_local_mode_v1') : false;
      const isAuthenticated = !!authUserPresent;

      return `
        ${localMode ? `
        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">Database Authentication</div>
          </div>
          <div style="margin-bottom: 12px; color: #f59e0b;">
            ⚠️ You are currently in Local Mode. Database features are unavailable.
          </div>
          <button class="odin-btn odin-btn-primary" onclick="window.OdinUI.authenticateWithDatabase()" style="width: 100%;">
            Authenticate with Database
          </button>
        </div>
        ` : (isAuthenticated ? `
        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">Database Authentication</div>
          </div>
          <div style="color: #22c55e;">
            ✓ Authenticated with database
          </div>
        </div>
        ` : '')}

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">API Keys</div>
          </div>

          <div class="odin-form-group">
            <label class="odin-form-label">
              Torn API Key
              ${tornKeyExists ? '<span class="odin-badge success">Configured</span>' : '<span class="odin-badge danger">Required</span>'}
            </label>
            <input type="password" id="odin-torn-api-key" class="odin-input"
                   placeholder="${tornKeyExists ? 'Key saved - enter new key to change' : 'Enter your Torn API key'}"
                   data-has-key="${tornKeyExists}">
          </div>

          <div class="odin-form-group">
            <label class="odin-form-label">
              TornStats API Key
              ${tornStatsKeyExists ? '<span class="odin-badge success">Configured</span>' : '<span class="odin-badge neutral">Optional</span>'}
            </label>
            <input type="password" id="odin-tornstats-key" class="odin-input"
                   placeholder="${tornStatsKeyExists ? 'Key saved - enter new key to change' : 'Optional - for enhanced stats'}"
                   data-has-key="${tornStatsKeyExists}">
          </div>

          <div class="odin-form-group">
            <label class="odin-form-label">
              FFScouter API Key
              ${ffScouterKeyExists ? '<span class="odin-badge success">Configured</span>' : '<span class="odin-badge neutral">Optional</span>'}
            </label>
            <input type="password" id="odin-ffscouter-key" class="odin-input"
                   placeholder="${ffScouterKeyExists ? 'Key saved - enter new key to change' : 'Optional - for scouting data'}"
                   data-has-key="${ffScouterKeyExists}">
          </div>

          <button class="odin-btn odin-btn-primary" onclick="window.OdinUI.saveApiKeys()">
            💾 Save API Keys
          </button>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">⚙️ Preferences</div>
          </div>

          <div class="odin-checkbox-group">
            <input type="checkbox" id="odin-auto-score" ${settings.autoScore ? 'checked' : ''}>
            <label for="odin-auto-score">Auto-score targets on visit</label>
          </div>

          <div class="odin-checkbox-group">
            <input type="checkbox" id="odin-show-buttons" ${settings.showButtons !== false ? 'checked' : ''}>
            <label for="odin-show-buttons">Show buttons on profiles</label>
          </div>

          <div class="odin-checkbox-group">
            <input type="checkbox" id="odin-chain-alerts" ${settings.chainAlerts ? 'checked' : ''}>
            <label for="odin-chain-alerts">Enable chain alerts</label>
          </div>

          <div class="odin-form-group">
            <label class="odin-form-label">Claim Expiry (minutes)</label>
            <select id="odin-claim-expiry" class="odin-select">
              ${[5, 10, 15, 20, 30].map(m =>
                `<option value="${m}" ${settings.claimExpiry === m ? 'selected' : ''}>${m} minutes</option>`
              ).join('')}
            </select>
          </div>

          <button class="odin-btn odin-btn-secondary" onclick="window.OdinUI.savePreferences()">
            💾 Save Preferences
          </button>
        </div>

        <div class="odin-card">
          <div class="odin-card-header">
            <div class="odin-card-title">ℹ️ About</div>
          </div>
          <div style="font-size: 12px; color: #a0a0a0;">
            <div>Odin Faction Tools v${UI_VERSION}</div>
            <div>By BjornOdinsson89</div>
            <div style="margin-top: 8px;">
              Role: ${ctx.access?.getEffectiveRole?.() || 'Unknown'}
            </div>
          </div>
        </div>

        ${renderLogConsole()}
      `;
    }

    // ============================================
    // SETTINGS HANDLERS
    // ============================================
    function attachSettingsHandlers() {
      // Mark keys as dirty when user types
      ['odin-torn-api-key', 'odin-tornstats-key', 'odin-ffscouter-key'].forEach(id => {
        const input = document.getElementById(id);
        if (input) {
          input.addEventListener('input', () => {
            const keyType = id.replace('odin-', '').replace('-key', '').replace('-api', '');
            apiKeysDirty[keyType] = true;
          });
        }
      });
    }

    // ============================================
    // RENDER HELPERS
    // ============================================
    function renderRecentActivity() {
      const activity = ctx.spear?.getRecentActivity?.() || [];
      if (activity.length === 0) {
        return '<div style="text-align: center; padding: 10px;">No recent activity</div>';
      }

      return activity.slice(0, 5).map(a => `
        <div style="padding: 6px 0; border-bottom: 1px solid rgba(255,255,255,0.05);">
          ${a.icon || '📌'} ${a.message || 'Unknown activity'}
          <span style="float: right; color: #6b7280;">${formatTimeAgo(a.timestamp)}</span>
        </div>
      `).join('');
    }

    function renderTargetList(targets, claims) {
      const targetArray = Object.entries(targets);
      if (targetArray.length === 0) {
        return '<div class="odin-empty"><div class="odin-empty-icon">🎯</div>No targets added</div>';
      }

      return targetArray.map(([targetId, target]) => {
        const isClaimed = claims[targetId];
        const scoreClass = target.frekiScore >= 70 ? 'high' : target.frekiScore >= 40 ? 'medium' : 'low';

        return `
          <div class="odin-target-item ${isClaimed ? 'claimed' : ''}">
            <div class="odin-score ${scoreClass}">${target.frekiScore || '?'}</div>
            <div class="odin-target-info">
              <div class="odin-target-name">
                <a href="https://www.torn.com/profiles.php?XID=${targetId}" target="_blank">
                  ${escapeHtml(target.targetName || targetId)}
                </a>
              </div>
              <div class="odin-target-meta">
                Level ${target.level || '?'} · ${escapeHtml(target.factionName || 'No Faction')}
                ${isClaimed ? ` · <span class="odin-badge warning">Claimed</span>` : ''}
              </div>
            </div>
            <div class="odin-target-actions">
              ${!isClaimed ? `
                <button class="odin-btn odin-btn-small odin-btn-primary"
                        onclick="window.OdinUI.claimTarget('${targetId}')">Claim</button>
              ` : `
                <button class="odin-btn odin-btn-small odin-btn-secondary"
                        onclick="window.OdinUI.releaseClaim('${targetId}')">Release</button>
              `}
              <button class="odin-btn odin-btn-small odin-btn-danger"
                      onclick="window.OdinUI.removeTarget('${targetId}')">✕</button>
            </div>
          </div>
        `;
      }).join('');
    }

    function renderScheduleGrid(schedule, myId) {
      const days = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
      let html = '';

      for (let day = 0; day < 7; day++) {
        const daySchedule = schedule[day] || {};
        const filledSlots = Object.keys(daySchedule).length;
        const isMine = Object.values(daySchedule).some(s => s.playerId === myId);

        html += `
          <div class="odin-schedule-slot ${filledSlots > 0 ? 'filled' : 'empty'} ${isMine ? 'mine' : ''}"
               onclick="window.OdinUI.viewDaySchedule(${day})"
               title="${days[day]}: ${filledSlots} slots filled">
            <div style="font-weight: 600;">${days[day]}</div>
            <div style="font-size: 8px;">${filledSlots}/24</div>
          </div>
        `;
      }

      return html;
    }

    function renderHeatmap(heatmap) {
      const days = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
      const hours = Array.from({ length: 24 }, (_, i) => i);

      let html = '<div class="odin-heatmap-label"></div>';
      hours.forEach(h => {
        html += (h % 4 === 0) ? `<div class="odin-heatmap-label">${h}</div>` : `<div class="odin-heatmap-label"></div>`;
      });

      days.forEach((day, dayIndex) => {
        html += `<div class="odin-heatmap-label">${day}</div>`;
        hours.forEach(hour => {
          const key = `${dayIndex}_${hour}`;
          const value = heatmap[key] || 0;
          const color = getHeatmapColor(value);
          html += `<div class="odin-heatmap-cell" style="background: ${color};"
                        title="${day} ${hour}:00 - ${value} online"></div>`;
        });
      });

      return html;
    }

    function renderMemberList(members, presence) {
      const memberArray = Object.entries(members);
      if (memberArray.length === 0) {
        return '<div style="text-align: center; padding: 10px; color: #6b7280;">No members loaded</div>';
      }

      return memberArray.slice(0, 20).map(([id, member]) => {
        const status = presence[id]?.status || 'offline';
        const statusColor = status === 'online' ? '#22c55e' : status === 'away' ? '#f59e0b' : '#6b7280';

        return `
          <div class="odin-member-item">
            <div>
              <span class="odin-member-name">${escapeHtml(member.name || id)}</span>
              <div style="font-size: 10px; color: #6b7280;">Level ${member.level || '?'}</div>
            </div>
            <div class="odin-member-status" style="color: ${statusColor};">
              ● ${status}
            </div>
          </div>
        `;
      }).join('');
    }

    function renderFavoritesList(favorites) {
      const favArray = Object.entries(favorites);
      if (favArray.length === 0) {
        return '<div style="text-align: center; padding: 10px; color: #6b7280;">No favorites yet</div>';
      }

      return favArray.map(([id, fav]) => `
        <div class="odin-member-item">
          <a href="https://www.torn.com/profiles.php?XID=${id}" target="_blank" class="odin-member-name">
            ${escapeHtml(fav.name || id)}
          </a>
          <button class="odin-btn odin-btn-small odin-btn-danger"
                  onclick="window.OdinUI.removeFavorite('${id}')">✕</button>
        </div>
      `).join('');
    }

    function renderPersonalTargetsList(targets) {
      const targetArray = Object.entries(targets);
      if (targetArray.length === 0) {
        return '<div style="text-align: center; padding: 10px; color: #6b7280;">No personal targets</div>';
      }

      return targetArray.map(([id, target]) => `
        <div class="odin-member-item">
          <a href="https://www.torn.com/profiles.php?XID=${id}" target="_blank" class="odin-member-name">
            ${escapeHtml(target.name || id)}
          </a>
          <span class="odin-badge ${target.frekiScore >= 70 ? 'success' : target.frekiScore >= 40 ? 'warning' : 'danger'}">
            ${target.frekiScore || '?'}
          </span>
        </div>
      `).join('');
    }

    // ============================================
    // UTILITY FUNCTIONS
    // ============================================
    function escapeHtml(text) {
      const div = document.createElement('div');
      div.textContent = text;
      return div.innerHTML;
    }

    function formatChainTimer(timeout) {
      if (!timeout || timeout <= 0) return '00:00';
      const minutes = Math.floor(timeout / 60);
      const seconds = timeout % 60;
      return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
    }

    function getChainTimerClass(timeout) {
      if (!timeout || timeout <= 0) return 'danger';
      if (timeout < 60) return 'danger';
      if (timeout < 180) return 'warning';
      return 'safe';
    }

    function formatTimeAgo(timestamp) {
      if (!timestamp) return 'unknown';
      const seconds = Math.floor((Date.now() - timestamp) / 1000);
      if (seconds < 60) return 'just now';
      if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
      if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
      return `${Math.floor(seconds / 86400)}d ago`;
    }

    function getHeatmapColor(value) {
      if (value >= 8) return 'rgba(34, 197, 94, 0.8)';
      if (value >= 4) return 'rgba(245, 158, 11, 0.8)';
      if (value >= 1) return 'rgba(239, 68, 68, 0.5)';
      return 'rgba(107, 114, 128, 0.3)';
    }

    // ============================================
    // PANEL CONTROLS
    // ============================================
    function togglePanel() {
      isVisible = !isVisible;
      const overlay = document.getElementById('odin-overlay');

      panelElement.classList.toggle('visible', isVisible);
      toggleButton.classList.toggle('active', isVisible);
      if (overlay) overlay.classList.toggle('visible', isVisible);

      if (isVisible) renderTabContent(activeTab);
    }

    function showPanel() {
      isVisible = true;
      const overlay = document.getElementById('odin-overlay');

      panelElement.classList.add('visible');
      toggleButton.classList.add('active');
      if (overlay) overlay.classList.add('visible');

      renderTabContent(activeTab);
    }

    function hidePanel() {
      isVisible = false;
      const overlay = document.getElementById('odin-overlay');

      panelElement.classList.remove('visible');
      toggleButton.classList.remove('active');
      if (overlay) overlay.classList.remove('visible');
    }

    // ============================================
    // NOTIFICATIONS
    // ============================================
    function showToast(message, type = 'info') {
      const existing = document.querySelector('.odin-toast');
      if (existing) existing.remove();

      const toast = document.createElement('div');
      toast.className = `odin-toast ${type}`;
      toast.textContent = message;
      document.body.appendChild(toast);

      setTimeout(() => { toast.remove(); }, 4000);
    }

    // ============================================
    // PUBLIC API ACTIONS
    // ============================================
    window.OdinUI = {
      refreshClaims: () => {
        nexus.emit?.('REFRESH_CLAIMS');
        showToast('Refreshing claims...', 'info');
      },
      addTarget: () => {
        const input = document.getElementById('odin-add-target-input');
        if (input?.value) {
          const targetId = input.value.trim();
          if (!targetId) {
            showToast('Please enter a valid target ID', 'error');
            return;
          }
          nexus.emit?.('ADD_TARGET', { targetId });
          input.value = '';
          showToast('Adding target...', 'success');
        } else {
          showToast('Please enter a target ID', 'error');
        }
      },
      claimTarget: (targetId) => {
        nexus.emit?.('CLAIM_TARGET', { targetId, type: 'attack' });
        showToast('Claiming target...', 'success');
      },
      releaseClaim: (targetId) => {
        nexus.emit?.('RELEASE_CLAIM', { targetId });
        showToast('Releasing claim...', 'info');
      },
      removeTarget: (targetId) => {
        if (confirm('Are you sure you want to remove this target?')) {
          nexus.emit?.('REMOVE_TARGET', { targetId });
          showToast('Target removed', 'success');
          setTimeout(() => renderTabContent('targets'), 500);
        }
      },
      scoreAllTargets: () => {
        nexus.emit?.('SCORE_ALL_TARGETS');
        showToast('Scoring all targets...', 'info');
      },
      startWatching: () => {
        nexus.emit?.('START_WATCHING');
        showToast('Watch mode activated', 'success');
      },
      alertChain: () => {
        nexus.emit?.('ALERT_CHAIN');
        showToast('Chain alert sent!', 'warning');
      },
      signUpForSlot: () => {
        const day = document.getElementById('odin-schedule-day')?.value;
        const hour = document.getElementById('odin-schedule-hour')?.value;
        if (day !== undefined && hour !== undefined) {
          nexus.emit?.('SIGN_UP_SLOT', { day: parseInt(day), hour: parseInt(hour) });
          showToast('Signed up for slot!', 'success');
        } else {
          showToast('Please select a day and hour', 'error');
        }
      },
      viewDaySchedule: (day) => {
        nexus.emit?.('VIEW_DAY_SCHEDULE', { day });
        showToast('Loading schedule...', 'info');
      },
      removeFavorite: (targetId) => {
        nexus.emit?.('REMOVE_FAVORITE', { targetId });
        showToast('Favorite removed', 'success');
        setTimeout(() => renderTabContent('personal'), 500);
      },
      getRecommendations: () => {
        nexus.emit?.('GET_RECOMMENDATIONS');
        showToast('Getting AI recommendations...', 'info');
      },
      exportData: () => {
        nexus.emit?.('EXPORT_DATA');
        showToast('Exporting data...', 'info');
      },
      clearExpired: () => {
        if (confirm('Clear all expired claims and targets?')) {
          nexus.emit?.('CLEAR_EXPIRED');
          showToast('Clearing expired items...', 'success');
        }
      },

      // FIXED: Only save keys that were actually changed
      saveApiKeys: () => {
        const tornKeyInput = document.getElementById('odin-torn-api-key');
        const tornStatsKeyInput = document.getElementById('odin-tornstats-key');
        const ffScouterKeyInput = document.getElementById('odin-ffscouter-key');

        const tornKey = tornKeyInput?.value?.trim();
        const tornStatsKey = tornStatsKeyInput?.value?.trim();
        const ffScouterKey = ffScouterKeyInput?.value?.trim();

        try {
          if (tornKey && tornKey.length > 8) ctx.api?.setTornApiKey?.(tornKey, { persist: true, silent: true });
          if (tornStatsKey && tornStatsKey.length > 8) ctx.api?.setTornStatsApiKey?.(tornStatsKey, { persist: true, silent: true });
          if (ffScouterKey && ffScouterKey.length > 8) ctx.api?.setFFScouterApiKey?.(ffScouterKey, { persist: true, silent: true });

          if (tornKeyInput) tornKeyInput.value = '';
          if (tornStatsKeyInput) tornStatsKeyInput.value = '';
          if (ffScouterKeyInput) ffScouterKeyInput.value = '';

          apiKeysDirty = { torn: false, tornStats: false, ffScouter: false };
          showToast('API keys saved locally!', 'success');
          renderTabContent('settings');
        } catch (e) {
          showToast('Failed to save API keys: ' + (e && e.message ? e.message : String(e)), 'error');
        }
      },

      savePreferences: () => {
        try {
          const prefs = {
            autoScore: document.getElementById('odin-auto-score')?.checked,
            showButtons: document.getElementById('odin-show-buttons')?.checked,
            chainAlerts: document.getElementById('odin-chain-alerts')?.checked,
            claimExpiry: parseInt(document.getElementById('odin-claim-expiry')?.value) || 10
          };

          const settings = { ...ctx.settings, ...prefs };
          if (ctx.saveSettings && typeof ctx.saveSettings === 'function') {
            ctx.saveSettings(settings);
          }
          nexus.emit?.('SAVE_PREFERENCES', prefs);
          showToast('Preferences saved successfully!', 'success');
        } catch (e) {
          showToast('Failed to save preferences: ' + (e && e.message ? e.message : String(e)), 'error');
        }
      },

      authenticateWithDatabase: () => {
        // Clear local mode flag
        if (storage && typeof storage.setJSON === 'function') {
          storage.setJSON('odin_local_mode_v1', false);
        }
        showToast('Switching to database authentication...', 'info');
        // Switch to War Room tab to trigger auth gate
        setTimeout(() => {
          switchTab('warRoom');
        }, 800);
      },

      // Log Console Functions
      filterLogs: () => {
        const logManager = ctx.logManager || window.OdinLogManager;
        if (!logManager) {
          showToast('Log manager not available', 'error');
          return;
        }

        const typeSelect = document.getElementById('odin-log-filter-type');
        const searchInput = document.getElementById('odin-log-search');
        const type = typeSelect ? typeSelect.value : 'all';
        const search = searchInput ? searchInput.value : '';

        const filteredLogs = logManager.getLogs({
          type: type,
          limit: 50,
          search: search || null
        });

        const logConsole = document.getElementById('odin-log-console');
        if (logConsole) {
          logConsole.innerHTML = renderLogEntries(filteredLogs);
        }

        showToast(`Filtered ${filteredLogs.length} logs`, 'info');
      },

      refreshLogs: () => {
        try {
          renderTabContent('settings');
          showToast('Logs refreshed successfully', 'success');
        } catch (e) {
          showToast('Failed to refresh logs', 'error');
        }
      },

      copyLogs: async () => {
        const logManager = ctx.logManager || window.OdinLogManager;
        if (!logManager) {
          showToast('Log manager not available', 'error');
          return;
        }

        try {
          const typeSelect = document.getElementById('odin-log-filter-type');
          const searchInput = document.getElementById('odin-log-search');
          const type = typeSelect ? typeSelect.value : 'all';
          const search = searchInput ? searchInput.value : '';

          const logsText = logManager.exportLogsRedacted({
            type: type,
            limit: 500,
            search: search || null
          });

          // Copy to clipboard
          if (navigator.clipboard && navigator.clipboard.writeText) {
            await navigator.clipboard.writeText(logsText);
            showToast('Logs copied to clipboard!', 'success');
          } else {
            // Fallback for older browsers
            const textarea = document.createElement('textarea');
            textarea.value = logsText;
            textarea.style.position = 'fixed';
            textarea.style.opacity = '0';
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            showToast('Logs copied to clipboard!', 'success');
          }
        } catch (error) {
          showToast('Failed to copy logs: ' + error.message, 'error');
        }
      },

      sendLogsToBjorn: async () => {
        const logManager = ctx.logManager || window.OdinLogManager;
        if (!logManager) {
          showToast('Log manager not available', 'error');
          return;
        }

        try {
          const typeSelect = document.getElementById('odin-log-filter-type');
          const searchInput = document.getElementById('odin-log-search');
          const type = typeSelect ? typeSelect.value : 'all';
          const search = searchInput ? searchInput.value : '';

          const result = await logManager.emailLogs('bjornodinsson89@gmail.com', {
            type: type,
            limit: 500,
            search: search || null
          });

          if (result.success) {
            showToast('Opening email client...', 'success');
          } else {
            showToast('Failed to send logs: ' + result.message, 'error');
          }
        } catch (error) {
          showToast('Failed to send logs: ' + error.message, 'error');
        }
      },

      clearLogs: () => {
        const logManager = ctx.logManager || window.OdinLogManager;
        if (!logManager) {
          showToast('Log manager not available', 'error');
          return;
        }

        if (confirm('Are you sure you want to clear all logs? This cannot be undone.')) {
          const typeSelect = document.getElementById('odin-log-filter-type');
          const type = typeSelect ? typeSelect.value : 'all';

          logManager.clearLogs(type);
          renderTabContent('settings');
          showToast('Logs cleared', 'success');
        }
      },

      showToast,
      refresh: () => renderTabContent(activeTab)
    };

    // ============================================
    // MODULE LIFECYCLE
    // ============================================
    function init() {
      log('[UIManager] ========================================');
      log('[UIManager] INITIALIZING UI MANAGER v' + UI_VERSION);
      log('[UIManager] ========================================');

      log('[UIManager] Step 1/3: Injecting CSS styles...');
      injectStyles();
      log('[UIManager] ✓ Styles injected');

      log('[UIManager] Step 2/3: Creating toggle button...');
      createToggleButton();
      log('[UIManager] ✓ Toggle button created (should be visible bottom-left)');

      log('[UIManager] Step 3/3: Creating main panel...');
      createPanel();
      log('[UIManager] ✓ Main panel created (hidden until toggle clicked)');

      // Subscribe to state changes
      nexus.on?.('STATE_CHANGED', () => {
        if (isVisible) renderTabContent(activeTab);
      });

      // Update connection status
      nexus.on?.('FIREBASE_CONNECTED', () => {
        firebaseConnected = true;
        const dot = document.getElementById('odin-status-dot');
        const text = document.getElementById('odin-status-text');

        if (dot) dot.className = 'odin-status-dot';
        if (text) text.textContent = 'Online';

        // Re-render current tab if visible and was previously gated
        if (isVisible && AUTH_REQUIRED_TABS.has(activeTab) && !authUserPresent) {
          renderTabContent(activeTab);
        }
      });

      nexus.on?.('FIREBASE_DISCONNECTED', () => {
        firebaseConnected = false;
        authUserPresent = false;

        const dot = document.getElementById('odin-status-dot');
        const text = document.getElementById('odin-status-text');

        if (dot) dot.className = 'odin-status-dot connecting';
        if (text) text.textContent = 'Offline';

        if (isVisible && AUTH_REQUIRED_TABS.has(activeTab)) {
          renderTabContent(activeTab);
        }
      });

      nexus.on?.('AUTH_STATE_CHANGED', (payload) => {
        authUserPresent = !!payload?.user;
        if (isVisible && AUTH_REQUIRED_TABS.has(activeTab)) {
          renderTabContent(activeTab);
        }
      });

      nexus.on?.('AUTH_SUCCESS', (payload) => {
        const playerName = payload?.playerName || 'User';
        const factionName = payload?.factionName || 'No faction';
        const message = `✓ Signed in as ${playerName} [${factionName}]`;
        log('[UIManager] AUTH_SUCCESS:', message);
        showToast(message, 'success');
      });

      // Listen for Firebase unavailable event
      nexus.on?.('FIREBASE_UNAVAILABLE', () => {
        log('[UIManager] Firebase unavailable - UI will work in offline mode');
      });

      log('[UIManager] ========================================');
      log('[UIManager] ✓ UI MANAGER READY');
      log('[UIManager] ✓ Event listeners registered');
      log('[UIManager] ✓ Toggle button active');
      log('[UIManager] ========================================');
    }

    function destroy() {
      log('[UIManager] Destroying...');

      if (panelElement) panelElement.remove();
      if (toggleButton) toggleButton.remove();

      const overlay = document.getElementById('odin-overlay');
      if (overlay) overlay.remove();

      const styles = document.getElementById('odin-ui-styles');
      if (styles) styles.remove();

      window.OdinUI = null;
      log('[UIManager] Destroyed');
    }

    return {
      id: 'odin-ui-manager',
      init,
      destroy,
      showToast,
      showPanel,
      hidePanel,
      refresh: () => renderTabContent(activeTab)
    };
  });
})();
